/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ca.jonestremblay.ui;

import javax.swing.JFrame;

/**
 *
 * @author jonat
 */
public class FenSplash extends javax.swing.JFrame {

    FenGUI fenGUI;
    /**
     * Creates new form SplashScreenà
     */
    public FenSplash(JFrame fenGUI) {
        this.setUndecorated(true);
        initComponents();
        this.setVisible(true);
        startProgressBar(fenGUI);
    }

    public void startProgressBar(JFrame fenGUI){
       // progressBar.setForeground(Color.blue);
        progressBar.setValue(0);
        progressBar.setString("Connexion au service en cours ...");
        try {
            for (int i=0; i <= 100; i++){
                if (i == 60){
                    progressBar.setString("Initialisation des variables d'environnement ...");
                   ((FenGUI)fenGUI).getPublicIPAddress();
                } else if (i > 60){
                    progressBar.setString("Connecté !");
                }
                Thread.sleep(30);
                progressBar.setValue(i);
            }
        } catch (Exception ex){
            
        }
    }
    
    public void launchApp(){
        fenGUI = new FenGUI();
        fenGUI.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        fenGUI.setVisible(false);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        progressBar = new javax.swing.JProgressBar();
        lblAppTitle = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setForeground(java.awt.Color.black);
        setMinimumSize(new java.awt.Dimension(460, 230));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        progressBar.setBackground(new java.awt.Color(65, 239, 221));
        progressBar.setForeground(new java.awt.Color(255, 102, 0));
        progressBar.setStringPainted(true);
        getContentPane().add(progressBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 390, 40));

        lblAppTitle.setFont(new java.awt.Font("Agency FB", 0, 8)); // NOI18N
        lblAppTitle.setIcon(new javax.swing.ImageIcon("C:\\Users\\jonat\\Downloads\\splash.png")); // NOI18N
        getContentPane().add(lblAppTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FenSplash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FenSplash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FenSplash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FenSplash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FenSplash(new FenGUI()).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblAppTitle;
    private javax.swing.JProgressBar progressBar;
    // End of variables declaration//GEN-END:variables
}
