//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BirthServiceDAO_WCF.entities
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/BirthServiceDAO_WCF.entities")]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.DateTime BirthDateField;
        
        private string EntryDateField;
        
        private string HostNameField;
        
        private string LOCAL_IP_AddressField;
        
        private string PUBLIC_IP_AddressField;
        
        private string UserNameField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime BirthDate
        {
            get
            {
                return this.BirthDateField;
            }
            set
            {
                this.BirthDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EntryDate
        {
            get
            {
                return this.EntryDateField;
            }
            set
            {
                this.EntryDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HostName
        {
            get
            {
                return this.HostNameField;
            }
            set
            {
                this.HostNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LOCAL_IP_Address
        {
            get
            {
                return this.LOCAL_IP_AddressField;
            }
            set
            {
                this.LOCAL_IP_AddressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PUBLIC_IP_Address
        {
            get
            {
                return this.PUBLIC_IP_AddressField;
            }
            set
            {
                this.PUBLIC_IP_AddressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName
        {
            get
            {
                return this.UserNameField;
            }
            set
            {
                this.UserNameField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IUserCatalogDAO")]
public interface IUserCatalogDAO
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserCatalogDAO/InsertNewUser", ReplyAction="http://tempuri.org/IUserCatalogDAO/InsertNewUserResponse")]
    bool InsertNewUser(BirthServiceDAO_WCF.entities.User user);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserCatalogDAO/InsertNewUser", ReplyAction="http://tempuri.org/IUserCatalogDAO/InsertNewUserResponse")]
    System.Threading.Tasks.Task<bool> InsertNewUserAsync(BirthServiceDAO_WCF.entities.User user);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserCatalogDAO/GetAllUsers", ReplyAction="http://tempuri.org/IUserCatalogDAO/GetAllUsersResponse")]
    BirthServiceDAO_WCF.entities.User[] GetAllUsers();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserCatalogDAO/GetAllUsers", ReplyAction="http://tempuri.org/IUserCatalogDAO/GetAllUsersResponse")]
    System.Threading.Tasks.Task<BirthServiceDAO_WCF.entities.User[]> GetAllUsersAsync();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserCatalogDAO/GetUsersByDateOfBirth", ReplyAction="http://tempuri.org/IUserCatalogDAO/GetUsersByDateOfBirthResponse")]
    BirthServiceDAO_WCF.entities.User[] GetUsersByDateOfBirth(string dateOfBirth);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserCatalogDAO/GetUsersByDateOfBirth", ReplyAction="http://tempuri.org/IUserCatalogDAO/GetUsersByDateOfBirthResponse")]
    System.Threading.Tasks.Task<BirthServiceDAO_WCF.entities.User[]> GetUsersByDateOfBirthAsync(string dateOfBirth);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserCatalogDAO/GetUsersAfterDateOfBirth", ReplyAction="http://tempuri.org/IUserCatalogDAO/GetUsersAfterDateOfBirthResponse")]
    BirthServiceDAO_WCF.entities.User[] GetUsersAfterDateOfBirth(string dateOfBirth);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserCatalogDAO/GetUsersAfterDateOfBirth", ReplyAction="http://tempuri.org/IUserCatalogDAO/GetUsersAfterDateOfBirthResponse")]
    System.Threading.Tasks.Task<BirthServiceDAO_WCF.entities.User[]> GetUsersAfterDateOfBirthAsync(string dateOfBirth);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserCatalogDAO/GetUsersBeforeDateOfBirth", ReplyAction="http://tempuri.org/IUserCatalogDAO/GetUsersBeforeDateOfBirthResponse")]
    BirthServiceDAO_WCF.entities.User[] GetUsersBeforeDateOfBirth(string dateOfBirth);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserCatalogDAO/GetUsersBeforeDateOfBirth", ReplyAction="http://tempuri.org/IUserCatalogDAO/GetUsersBeforeDateOfBirthResponse")]
    System.Threading.Tasks.Task<BirthServiceDAO_WCF.entities.User[]> GetUsersBeforeDateOfBirthAsync(string dateOfBirth);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserCatalogDAO/GetUsersByDateEntryRange", ReplyAction="http://tempuri.org/IUserCatalogDAO/GetUsersByDateEntryRangeResponse")]
    BirthServiceDAO_WCF.entities.User[] GetUsersByDateEntryRange(string minimalDate, string maximumDate);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserCatalogDAO/GetUsersByDateEntryRange", ReplyAction="http://tempuri.org/IUserCatalogDAO/GetUsersByDateEntryRangeResponse")]
    System.Threading.Tasks.Task<BirthServiceDAO_WCF.entities.User[]> GetUsersByDateEntryRangeAsync(string minimalDate, string maximumDate);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserCatalogDAO/GetUsersByEntryDateTimeline", ReplyAction="http://tempuri.org/IUserCatalogDAO/GetUsersByEntryDateTimelineResponse")]
    BirthServiceDAO_WCF.entities.User[] GetUsersByEntryDateTimeline(string timeline);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserCatalogDAO/GetUsersByEntryDateTimeline", ReplyAction="http://tempuri.org/IUserCatalogDAO/GetUsersByEntryDateTimelineResponse")]
    System.Threading.Tasks.Task<BirthServiceDAO_WCF.entities.User[]> GetUsersByEntryDateTimelineAsync(string timeline);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserCatalogDAO/GetUsersByPublicIP", ReplyAction="http://tempuri.org/IUserCatalogDAO/GetUsersByPublicIPResponse")]
    BirthServiceDAO_WCF.entities.User[] GetUsersByPublicIP(string publicIP);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserCatalogDAO/GetUsersByPublicIP", ReplyAction="http://tempuri.org/IUserCatalogDAO/GetUsersByPublicIPResponse")]
    System.Threading.Tasks.Task<BirthServiceDAO_WCF.entities.User[]> GetUsersByPublicIPAsync(string publicIP);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserCatalogDAO/GetByUsername", ReplyAction="http://tempuri.org/IUserCatalogDAO/GetByUsernameResponse")]
    BirthServiceDAO_WCF.entities.User[] GetByUsername(string username);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserCatalogDAO/GetByUsername", ReplyAction="http://tempuri.org/IUserCatalogDAO/GetByUsernameResponse")]
    System.Threading.Tasks.Task<BirthServiceDAO_WCF.entities.User[]> GetByUsernameAsync(string username);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserCatalogDAO/GetByUsernamePattern", ReplyAction="http://tempuri.org/IUserCatalogDAO/GetByUsernamePatternResponse")]
    BirthServiceDAO_WCF.entities.User[] GetByUsernamePattern(string username);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserCatalogDAO/GetByUsernamePattern", ReplyAction="http://tempuri.org/IUserCatalogDAO/GetByUsernamePatternResponse")]
    System.Threading.Tasks.Task<BirthServiceDAO_WCF.entities.User[]> GetByUsernamePatternAsync(string username);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserCatalogDAO/GetUsersByDateEntry", ReplyAction="http://tempuri.org/IUserCatalogDAO/GetUsersByDateEntryResponse")]
    BirthServiceDAO_WCF.entities.User[] GetUsersByDateEntry(string entryDate);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserCatalogDAO/GetUsersByDateEntry", ReplyAction="http://tempuri.org/IUserCatalogDAO/GetUsersByDateEntryResponse")]
    System.Threading.Tasks.Task<BirthServiceDAO_WCF.entities.User[]> GetUsersByDateEntryAsync(string entryDate);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserCatalogDAO/GetUsersOlderThanAge", ReplyAction="http://tempuri.org/IUserCatalogDAO/GetUsersOlderThanAgeResponse")]
    BirthServiceDAO_WCF.entities.User[] GetUsersOlderThanAge(int age);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserCatalogDAO/GetUsersOlderThanAge", ReplyAction="http://tempuri.org/IUserCatalogDAO/GetUsersOlderThanAgeResponse")]
    System.Threading.Tasks.Task<BirthServiceDAO_WCF.entities.User[]> GetUsersOlderThanAgeAsync(int age);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserCatalogDAO/GetUsersByAgeRange", ReplyAction="http://tempuri.org/IUserCatalogDAO/GetUsersByAgeRangeResponse")]
    BirthServiceDAO_WCF.entities.User[] GetUsersByAgeRange(int minimalAge, int maximalAge);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserCatalogDAO/GetUsersByAgeRange", ReplyAction="http://tempuri.org/IUserCatalogDAO/GetUsersByAgeRangeResponse")]
    System.Threading.Tasks.Task<BirthServiceDAO_WCF.entities.User[]> GetUsersByAgeRangeAsync(int minimalAge, int maximalAge);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IUserCatalogDAOChannel : IUserCatalogDAO, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class UserCatalogDAOClient : System.ServiceModel.ClientBase<IUserCatalogDAO>, IUserCatalogDAO
{
    
    public UserCatalogDAOClient()
    {
    }
    
    public UserCatalogDAOClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public UserCatalogDAOClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public UserCatalogDAOClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public UserCatalogDAOClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public bool InsertNewUser(BirthServiceDAO_WCF.entities.User user)
    {
        return base.Channel.InsertNewUser(user);
    }
    
    public System.Threading.Tasks.Task<bool> InsertNewUserAsync(BirthServiceDAO_WCF.entities.User user)
    {
        return base.Channel.InsertNewUserAsync(user);
    }
    
    public BirthServiceDAO_WCF.entities.User[] GetAllUsers()
    {
        return base.Channel.GetAllUsers();
    }
    
    public System.Threading.Tasks.Task<BirthServiceDAO_WCF.entities.User[]> GetAllUsersAsync()
    {
        return base.Channel.GetAllUsersAsync();
    }
    
    public BirthServiceDAO_WCF.entities.User[] GetUsersByDateOfBirth(string dateOfBirth)
    {
        return base.Channel.GetUsersByDateOfBirth(dateOfBirth);
    }
    
    public System.Threading.Tasks.Task<BirthServiceDAO_WCF.entities.User[]> GetUsersByDateOfBirthAsync(string dateOfBirth)
    {
        return base.Channel.GetUsersByDateOfBirthAsync(dateOfBirth);
    }
    
    public BirthServiceDAO_WCF.entities.User[] GetUsersAfterDateOfBirth(string dateOfBirth)
    {
        return base.Channel.GetUsersAfterDateOfBirth(dateOfBirth);
    }
    
    public System.Threading.Tasks.Task<BirthServiceDAO_WCF.entities.User[]> GetUsersAfterDateOfBirthAsync(string dateOfBirth)
    {
        return base.Channel.GetUsersAfterDateOfBirthAsync(dateOfBirth);
    }
    
    public BirthServiceDAO_WCF.entities.User[] GetUsersBeforeDateOfBirth(string dateOfBirth)
    {
        return base.Channel.GetUsersBeforeDateOfBirth(dateOfBirth);
    }
    
    public System.Threading.Tasks.Task<BirthServiceDAO_WCF.entities.User[]> GetUsersBeforeDateOfBirthAsync(string dateOfBirth)
    {
        return base.Channel.GetUsersBeforeDateOfBirthAsync(dateOfBirth);
    }
    
    public BirthServiceDAO_WCF.entities.User[] GetUsersByDateEntryRange(string minimalDate, string maximumDate)
    {
        return base.Channel.GetUsersByDateEntryRange(minimalDate, maximumDate);
    }
    
    public System.Threading.Tasks.Task<BirthServiceDAO_WCF.entities.User[]> GetUsersByDateEntryRangeAsync(string minimalDate, string maximumDate)
    {
        return base.Channel.GetUsersByDateEntryRangeAsync(minimalDate, maximumDate);
    }
    
    public BirthServiceDAO_WCF.entities.User[] GetUsersByEntryDateTimeline(string timeline)
    {
        return base.Channel.GetUsersByEntryDateTimeline(timeline);
    }
    
    public System.Threading.Tasks.Task<BirthServiceDAO_WCF.entities.User[]> GetUsersByEntryDateTimelineAsync(string timeline)
    {
        return base.Channel.GetUsersByEntryDateTimelineAsync(timeline);
    }
    
    public BirthServiceDAO_WCF.entities.User[] GetUsersByPublicIP(string publicIP)
    {
        return base.Channel.GetUsersByPublicIP(publicIP);
    }
    
    public System.Threading.Tasks.Task<BirthServiceDAO_WCF.entities.User[]> GetUsersByPublicIPAsync(string publicIP)
    {
        return base.Channel.GetUsersByPublicIPAsync(publicIP);
    }
    
    public BirthServiceDAO_WCF.entities.User[] GetByUsername(string username)
    {
        return base.Channel.GetByUsername(username);
    }
    
    public System.Threading.Tasks.Task<BirthServiceDAO_WCF.entities.User[]> GetByUsernameAsync(string username)
    {
        return base.Channel.GetByUsernameAsync(username);
    }
    
    public BirthServiceDAO_WCF.entities.User[] GetByUsernamePattern(string username)
    {
        return base.Channel.GetByUsernamePattern(username);
    }
    
    public System.Threading.Tasks.Task<BirthServiceDAO_WCF.entities.User[]> GetByUsernamePatternAsync(string username)
    {
        return base.Channel.GetByUsernamePatternAsync(username);
    }
    
    public BirthServiceDAO_WCF.entities.User[] GetUsersByDateEntry(string entryDate)
    {
        return base.Channel.GetUsersByDateEntry(entryDate);
    }
    
    public System.Threading.Tasks.Task<BirthServiceDAO_WCF.entities.User[]> GetUsersByDateEntryAsync(string entryDate)
    {
        return base.Channel.GetUsersByDateEntryAsync(entryDate);
    }
    
    public BirthServiceDAO_WCF.entities.User[] GetUsersOlderThanAge(int age)
    {
        return base.Channel.GetUsersOlderThanAge(age);
    }
    
    public System.Threading.Tasks.Task<BirthServiceDAO_WCF.entities.User[]> GetUsersOlderThanAgeAsync(int age)
    {
        return base.Channel.GetUsersOlderThanAgeAsync(age);
    }
    
    public BirthServiceDAO_WCF.entities.User[] GetUsersByAgeRange(int minimalAge, int maximalAge)
    {
        return base.Channel.GetUsersByAgeRange(minimalAge, maximalAge);
    }
    
    public System.Threading.Tasks.Task<BirthServiceDAO_WCF.entities.User[]> GetUsersByAgeRangeAsync(int minimalAge, int maximalAge)
    {
        return base.Channel.GetUsersByAgeRangeAsync(minimalAge, maximalAge);
    }
}
